### PR TITLE
Add new map Tomb Raiders.

### PR DESCRIPTION
**Pull request by GraionDilach**
image

Depends on #168. Only the last two commits are new.

### CODE REVIEW

**Comment by GraionDilach** [comment]
Whoops, I have an error here. The small pyramid formulation on the middle right side is accidentally flipped.

**Comment by GraionDilach** [comment]
Fixed. I won't update the map preview though from the first post - the left edge was adjusted to mirror the right edge.

**Comment by GraionDilach** [comment]
Rebased.

**Comment by Mailaender** [comment]
The gold in the middle is unreachable, because you walled it off with cliffs.

**Comment by GraionDilach** [comment]
That is intentional and not unreachable. You're supposed to get a flying transport and a builder to place a storage there and then deliver miners manually.

**Pull request merged**
