### PR TITLE
Added prop18.

### PR DESCRIPTION
**Pull request by Dzierzan**
Supersedes #1136

prop18

### CODE REVIEW

**Review by OcelotWalrus — COMMENTED** [review]
The drilling animations look terrible in my honest opinion (it drills down way too fast). You should add outlines to the basements. The shadow should also be drawn over the center basement, logically. The shadow also looks odd but maybe that's just me.

**Comment by Dzierzan** [comment]
To be honest, it doesn't look like a drill to me, but more like a hammer-thingy. Hence pounding the hole, for whatever reason you might image. So your guess is as good as mine, but drill... I don't see it.

I prefer foundation without outline.

The shadow is correct.
image

**Comment by OcelotWalrus** [comment]
At least don't make the animation when it goes down that harsh, it doesn't feel natural.

**Comment by OcelotWalrus** [comment]
I'd just add one more frame though, at the middle of the descent.

**Comment by Dzierzan** [comment]
I can add that one frame, but I'd avoid using particles.

**Comment by Dzierzan** [comment]
Alright, I actually re-added your original idea of `active` sequence, as I forgot pre-placed props would have synchronized animation, which would look odd.

I also changed a bit animation. See if you like it now.

**Comment by Dzierzan** [comment]
Ehh... a small desync with shadow, gotta fix it. Barely noticable, but I see it xD

**Comment by Dzierzan** [comment]
prop18-2

**Review by OcelotWalrus — APPROVED** [review]

**Pull request merged**
