### PR TITLE
Replace the repair wrench with a ratchet.

### PR DESCRIPTION
**Pull request by GraionDilach**

### CODE REVIEW

**Comment by Mailaender** [comment]
The artwork looks way better, but contrast seems to be a problem.

**Comment by GraionDilach** [comment]
Increased the contrast on the handle. The head seemed to be fine from the get-go.

**Comment by Mailaender** [comment]
Maybe add a white outline? The grey looks very similar to the building grey.

**Comment by GraionDilach** [comment]
Everything has dark outlines in the source artwork. I'm not sure how to proceed.

**Comment by GraionDilach** [comment]
Another option for a followup could be to recolor the handle into player color. OpenRA has ally-repair and I'm not certain if it's enabled here (or should be).

**Comment by Mailaender** [comment]
That is a good idea. We probably want ally repair. I just didn't have art.

**Pull request merged**
