### PR TITLE
Updated Banshee's weapon artwork.

### PR DESCRIPTION
**Pull request by Dzierzan**
- Added bullet18 artwork.
- Changed trail image for Banshee's missile.
- Restored muzzle flash effect.
- Updated armament's LocalOffset.

### CODE REVIEW

**Review by OcelotWalrus — COMMENTED** [review]
It looks very cool but the effects fit more into Yuruki's theme.

**Comment by Dzierzan** [comment]
Maybe so, but it's still a missile.

**Comment by OcelotWalrus** [comment]
I reminds me the Stealth Tank missile.

**Comment by Dzierzan** [comment]
I can make a new trail.

**Comment by Dzierzan** [comment]
image

**Review by OcelotWalrus — APPROVED** [review]
This looks even better. I'd stick with that personally.

**Pull request merged**
