### PR TITLE
Added new map - Swamp Conquest (2P, Conquest)

### PR DESCRIPTION
**Pull request by OcelotWalrus**
This PR adds a new default conquest/multiplayer map to the HV mod.

* The map contains 3 iron deposits per player side, and 2 gold deposits. The middle has 2 gold deposits.
* Every player has 2 neutral extractor and a comlink to capture on his side. The mid has a tech reconstructor to capture, and a watchtower.

image

Here're some gameplay shots (_don't pay attention to the units, I'm using an edit of the HV mod made by myself_):

<details><summary>Roll Down</summary>

Screenshot from 2024-05-04 13-44-38
Screenshot from 2024-05-04 13-44-52
Screenshot from 2024-05-04 13-45-14
Screenshot from 2024-05-04 13-45-44
Screenshot from 2024-05-04 13-45-58
Screenshot from 2024-05-04 13-46-51
Screenshot from 2024-05-04 13-47-30
Screenshot from 2024-05-04 13-47-47

</details>

### CODE REVIEW

**Comment by Mailaender** [comment]
You only placed the lowest amount of resource. Is that on purpose, or did you not know that you can click on the resource spot again to increase the amount?

**Comment by OcelotWalrus** [comment]
> You only placed the lowest amount of resource. Is that on purpose, or did you not know that you can click on the resource spot again to increase the amount?

Oopsie. I just learned that. I'm modifying that right now. I know realize why when playing I was getting so little cash.

**Comment by OcelotWalrus** [comment]
Just did modifications on the deposits.

**Comment by Mailaender** [comment]
There is an imbalance. The amount of mined out spot differs. South-east in generals has more resources around the starting point. Gold is more valuable than iron.

grafik

**Comment by OcelotWalrus** [comment]
> The amount of mined out spot differs

It does not.

> South-east in generals has more resources around the starting point.

That's true. I'm gonna move the east starting point more to the bottom

> Gold is more valuable than iron.

Logic?

**Comment by OcelotWalrus** [comment]
image

**Comment by Mailaender** [comment]
I just fetched again and the map looks different from your screenshot. Maybe you forgot to push the latest changes.

**Comment by OcelotWalrus** [comment]
> I just fetched again and the map looks different from your screenshot. Maybe you forgot to push the latest changes.

I didn't yet. I just wanted your opinion on my changes from the screenshot, before pushing.

**Comment by GraionDilach** [comment]
I'm not sold on the difference between the orientation of the two corner outpost (bridge)s, it somewhat makes bottom left easier to defend headfront. On the other hand, right side lacks the straightforward-to-center path anyway, so yeah, this is kinda Westwoody "sorta-balanced" map design.

**Comment by Mailaender** [comment]
> I didn't yet. I just wanted your opinion on my changes from the screenshot, before pushing.

Your latest screenshot looks much better. I mostly care for an even distribution. The rest is up to you.

**Comment by OcelotWalrus** [comment]
> I'm not sold on the difference between the orientation of the two corner outpost (bridge)s, it somewhat makes bottom left easier to defend headfront. On the other hand, right side lacks the straightforward-to-center path anyway, so yeah, this is kinda Westwoody "sorta-balanced" map design.

Yeah, I'm not really good at making balanced stuff. I'm just good at making cool and un-balanced stuff ;)

**Comment by OcelotWalrus** [comment]
In my opinion it's about merge-ready.

**Comment by Mailaender** [comment]
This branch could not be merged due to conflicts so I squashed and cherry picked it https://github.com/OpenHV/OpenHV/commit/82fb39da62d7c5fef988715bc1573c49b322d9eb.

**Pull request closed without merging**
