### PR TITLE
Added a cruise missile that can be intercepted

### PR DESCRIPTION
**Pull request by Mailaender**
Followup of https://github.com/OpenHV/OpenHV/pull/331.

### CODE REVIEW

**Comment by Dzierzan** [comment]
Nice, but:

1. Lacks smoke trail for the missile.
2. It weirdly super accelerates when a projectile almost reaches a target.
3. The trajectory could look like more like an arc. Right now it feels like reverse "U" trajectory.
4. A projectile is too fast. Not sure if other missile/rocket projectiles can even reach it.

**Comment by Mailaender** [comment]
1. Added a smoke trail.
2. Decreased target acceleration.
3. That is on purpose as the missile shoots upwards and then locks onto target.
4. I reduced the speed by 15%.

**Comment by Dzierzan** [comment]
Can you move the projectile origin a bit to actor's back so it matches the hole better? Also there's no splash when the missile hits water and probably other fluids as well. I guess this is my oversight, you could update it as well.

**Comment by Dzierzan** [comment]
Hmm... maybe the explosion effect is too small for such missile. Let's use medium one instead.

**Comment by Mailaender** [comment]
Changed it to medium, which is indeed more satisfying.

**Pull request merged**
