### PR TITLE
Enlarged Lightning Tank

### PR DESCRIPTION
**Pull request by Dzierzan**
image

### CODE REVIEW

**Review by OcelotWalrus — APPROVED** [review]

**Comment by Mailaender** [comment]
They do overlap as they are larger than cell size, but it is actually worse for the APC.
grafik

**Comment by OcelotWalrus** [comment]
Maybe they would need a footprint? Just and idea like that.

**Comment by Mailaender** [comment]
Only buildings have footprints.

**Comment by OcelotWalrus** [comment]
But how other mods do? For example, D2K have units bigger than a cell, and they don't overlap.

**Comment by GraionDilach** [comment]
They do overlap. Other mods also ignore overlapping.

The engine lacks support for multicell units anyway.

**Pull request merged**
