### PR TITLE
Added force field effect artwork.

### PR DESCRIPTION
**Pull request by Dzierzan**
However `GrantExternalConditionPower ` doesn't support image effect. So for time being, only art is submitted.

### CODE REVIEW

**Review by OcelotWalrus — APPROVED** [review]
Ain't implemented yet, but looks nice! I like it.

**Comment by Dzierzan** [comment]
GIF for reference:
forceshieldeffect

**Comment by OcelotWalrus** [comment]
All the effects you're adding (comlink, force field etc...) are really nice. It really enhances the game's visuals.

**Comment by GraionDilach** [comment]
Looks too isometric and not enough topdown IMO.

**Comment by OcelotWalrus** [comment]
> Looks too isometric and not enough topdown IMO.

Maybe. But we need to see how it actually looks in-game to be sure.

**Comment by Mailaender** [comment]
I can't easily extend `GrantExternalConditionPower` for a sprite effect. However [GrantExternalConditionPower](https://openhv.readthedocs.io/en/latest/release/traits/#grantexternalconditionpower) already has support for an `active` sequence on the targeted actors.

**Comment by GraionDilach** [comment]
You missed the discussion from chat but I'll resummarize.

The `active` sequence is actually the same functionality what upstream's `WithSupportPowerActivationAnimation` trait does.
`DetonateWeaponPower` with a `GrantExternalConditionWarhead` can provide the needed functionality, but  it would need a restructuring of the setup and shifting footprint range for warhead spread range.

**Comment by Mailaender** [comment]
Ah `active` is on the building and not on the unit.

**Comment by GraionDilach** [comment]
I'm not sure why would you call anything of that as fake, though. I mean, the DWP weapon's explosion having a CreateEffectWarhead along is where this would be used.

**Pull request closed without merging**
