### PR TITLE
Remove Broker Pod deployable ability and prevent bots from building them

### PR DESCRIPTION
**Pull request by WilliamWeberBerrutti**

### CODE REVIEW

**Comment by GraionDilach** [comment]
Should aqlso delete the sequence definition at least to not waste pixels on the generated internal sprite sheets.

**Review by OcelotWalrus — COMMENTED** [review]
Why preventing the bots from building broker pods?

**Comment by WilliamWeberBerrutti** [comment]
> Why preventing the bots from building broker pods?

Because, with the ability removal, they don't know to use them to steal money, as far as I noticed.

**Comment by GraionDilach** [comment]
It's likely the same issue as upstream's takeaway from medics/mechanics then - the AI spamming attack-moves and relying on autotargeting thenafter is too crude to be effectively combined with such a specific attacking usecase.

**Pull request merged**
