### PR TITLE
Added extra road tiles for diagonal bridges.

### PR DESCRIPTION
**Pull request by Dzierzan**
image

### CODE REVIEW

**Comment by OcelotWalrus** [comment]
I appreciate that you did it so fast! but there're a few problems: 

338355676-fd5e53c4-b105-4c2b-acc5-00e7a00ea88a

338355676-fd5e53c4-b105-4c2b-acc5-00e7a00ea88a

338355676-fd5e53c4-b105-4c2b-acc5-00e7a00ea88a

Untitled

**Comment by Mailaender** [comment]
Why is it not diagonally shaped?

**Comment by Dzierzan** [comment]
HV has no true diagonal tiles anyway.

**Comment by Dzierzan** [comment]
The PR was updated. I removed extra shadow tiles and updated tiles to have water/lava/swamp parts darker. Here's the result.

image

So this way, any mapper won't have to understand MY thinking.

**Comment by Mailaender** [comment]
Minor problem with lava bridges:
grafik

**Comment by Mailaender** [comment]
grafik

**Comment by Dzierzan** [comment]
OK, should be better now.

**Pull request merged**
